services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
  app:
    build: .
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      DB_HOST:     ${DB_HOST}
      DB_PORT:     ${DB_PORT}
      DB_NAME:     ${DB_NAME}
      DB_USER:     ${DB_USER}
      DB_PASS:     ${DB_PASS}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
    jenkins_home:
