services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  app:
    build:
      context: .
      dockerfile: Dockerfile  # o el que estés usando para tu app
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  tomcat:
    image: tomcat:9.0
    ports:
      - "8081:8080"  # Usa un puerto libre
    volumes:
      - ./target/HotelTransito.war:/usr/local/tomcat/webapps/HotelTransito.war

volumes:
  jenkins_home:

